name: Ilija Eftimov
description: Rubyist, open source afficionado, whatever
meta_description: "Rubyist, open source afficionado, whatever"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://eftimov.net'
google_analytics: 'UA-XXXXXXXX-X'
cover: 'assets/images/cover.jpeg'
profile_image: 'assets/images/profile.jpg'
permalink: :title


github: "fteem"
linkedin: ""
twitter: "fteem"
email: "ileeftimov+blog@gmail.com"


# Details for the RSS feed generator
url:            'eftimov.net'
author:         'Ilija Eftimov'
